"""Generate src/science/teos10.generated.ts from the official GSW-C source.

The 75-term polynomial of Roquet et al. (2015) is transcribed mechanically
so no coefficient is typed by hand. Usage:
    python tools/gen_teos10.py <path-to-gsw-C-src-dir> > src/science/teos10.generated.ts
"""
import re
import sys
from pathlib import Path

src = Path(sys.argv[1])
toolbox = (src / "gsw_oceanographic_toolbox.c").read_text()
consts = (src / "gsw_internal_const.h").read_text()

FUNCS = [
    "gsw_specvol", "gsw_alpha", "gsw_beta", "gsw_sound_speed", "gsw_sigma0",
    "gsw_specvol_sso_0", "gsw_enthalpy_sso_0", "gsw_grav", "gsw_ct_freezing_poly",
    "gsw_z_from_p", "gsw_p_from_z",
]


def macro(name: str) -> str:
    m = re.search(r"#define %s \\\n(.*?)(?<!\\)\n" % name, consts, re.S)
    body = m.group(1)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = body.replace("\\\n", "\n")
    body = re.sub(r"\b(UNUSED|double)\b", "", body)
    out = []
    for part in body.split(","):
        part = part.strip().rstrip(";").strip()
        if not part:
            continue
        name_, val = [s.strip() for s in part.split("=", 1)]
        out.append((name_, val))
    return out


def func_body(name: str) -> tuple[str, str]:
    m = re.search(r"^double\n%s\((.*?)\)\n\{\n(.*?)\n\}" % name, toolbox, re.S | re.M)
    if not m:
        raise SystemExit("function not found: " + name)
    return m.group(1), m.group(2)


def to_ts(name: str) -> str:
    args, body = func_body(name)
    args_ts = ", ".join(a.replace("double", "").strip() + ": number" for a in args.split(","))
    body = re.sub(r"^\s*GSW_\w+;\s*$", "", body, flags=re.M)
    body = re.sub(r"^\s*double\s+([^;]*);", lambda m: "let " + m.group(1) + ";", body, flags=re.M)
    body = re.sub(r"\b(sqrt|sin|cos|pow|exp|log)\(", r"Math.\1(", body)
    body = re.sub(r"\bgsw_(\w+)\(", lambda m: m.group(1) + "(", body)
    ts_name = name[len("gsw_"):]
    return f"export function {ts_name}({args_ts}): number {{\n{body}\n}}\n"


print("// AUTO-GENERATED by tools/gen_teos10.py from GSW-C (TEOS-10, BSD-3-Clause).")
print("// Do not edit by hand. Reference: IOC, SCOR & IAPSO (2010); Roquet et al. (2015).")
print("/* eslint-disable */")
print("const GSW_INVALID_VALUE = NaN;")
seen = set()
for group in ["GSW_TEOS10_CONSTANTS", "GSW_SPECVOL_COEFFICIENTS", "GSW_FREEZING_POLY_COEFFICIENTS"]:
    for n, v in macro(group):
        if n in seen:
            continue
        seen.add(n)
        v = re.sub(r"\bgsw_(\w+)", r"gsw_\1", v)
        print(f"const {n} = {v};")
print()
for f in FUNCS:
    print(to_ts(f))
