// AUTO-GENERATED by tools/gen_teos10.py from GSW-C (TEOS-10, BSD-3-Clause).
// Do not edit by hand. Reference: IOC, SCOR & IAPSO (2010); Roquet et al. (2015).
/* eslint-disable */
const GSW_INVALID_VALUE = NaN;
const db2pa = 1.0e4;
const rec_db2pa = 1.0e-4;
const pa2db = 1.0e-4;
const rec_pa2db = 1.0e4;
const pi = 3.141592653589793;
const deg2rad = pi/180.0;
const rad2deg = 180.0/pi;
const gamma = 2.26e-7;
const gsw_cp0 = 3991.86795711963;
const gsw_t0 = 273.15;
const gsw_p0 = 101325.0;
const gsw_sso = 35.16504;
const gsw_sqrtsso = 5.930011804372737;
const gsw_ups = gsw_sso/35.0;
const gsw_sfac = 0.0248826675584615;
const offset = 5.971840214030754e-1;
const gsw_c3515 = 42.9140;
const gsw_soncl = 1.80655;
const gsw_valence_factor = 1.2452898;
const gsw_atomic_weight = 31.4038218;
const a000 = -1.56497346750e-5;
const a001 = 1.85057654290e-5;
const a002 = -1.17363867310e-6;
const a003 = -3.65270065530e-7;
const a004 = 3.14540999020e-7;
const a010 = 5.55242129680e-5;
const a011 = -2.34332137060e-5;
const a012 = 4.26100574800e-6;
const a013 = 5.73918103180e-7;
const a020 = -4.95634777770e-5;
const a021 = 2.37838968519e-5;
const a022 = -1.38397620111e-6;
const a030 = 2.76445290808e-5;
const a031 = -1.36408749928e-5;
const a032 = -2.53411666056e-7;
const a040 = -4.02698077700e-6;
const a041 = 2.53683834070e-6;
const a050 = 1.23258565608e-6;
const a100 = 3.50095997640e-5;
const a101 = -9.56770881560e-6;
const a102 = -5.56991545570e-6;
const a103 = -2.72956962370e-7;
const a110 = -7.48716846880e-5;
const a111 = -4.73566167220e-7;
const a112 = 7.82747741600e-7;
const a120 = 7.24244384490e-5;
const a121 = -1.03676320965e-5;
const a122 = 2.32856664276e-8;
const a130 = -3.50383492616e-5;
const a131 = 5.18268711320e-6;
const a140 = -1.65263794500e-6;
const a200 = -4.35926785610e-5;
const a201 = 1.11008347650e-5;
const a202 = 5.46207488340e-6;
const a210 = 7.18156455200e-5;
const a211 = 5.85666925900e-6;
const a212 = -1.31462208134e-6;
const a220 = -4.30608991440e-5;
const a221 = 9.49659182340e-7;
const a230 = 1.74814722392e-5;
const a300 = 3.45324618280e-5;
const a301 = -9.84471178440e-6;
const a302 = -1.35441856270e-6;
const a310 = -3.73971683740e-5;
const a311 = -9.76522784000e-7;
const a320 = 6.85899736680e-6;
const a400 = -1.19594097880e-5;
const a401 = 2.59092252600e-6;
const a410 = 7.71906784880e-6;
const a500 = 1.38645945810e-6;
const b000 = -3.10389819760e-4;
const b003 = 3.63101885150e-7;
const b004 = -1.11471254230e-7;
const b010 = 3.50095997640e-5;
const b013 = -2.72956962370e-7;
const b020 = -3.74358423440e-5;
const b030 = 2.41414794830e-5;
const b040 = -8.75958731540e-6;
const b050 = -3.30527589000e-7;
const b100 = 1.33856134076e-3;
const b103 = 3.34926075600e-8;
const b110 = -8.71853571220e-5;
const b120 = 7.18156455200e-5;
const b130 = -2.87072660960e-5;
const b140 = 8.74073611960e-6;
const b200 = -2.55143801811e-3;
const b210 = 1.03597385484e-4;
const b220 = -5.60957525610e-5;
const b230 = 6.85899736680e-6;
const b300 = 2.32344279772e-3;
const b310 = -4.78376391520e-5;
const b320 = 1.54381356976e-5;
const b400 = -1.05461852535e-3;
const b410 = 6.93229729050e-6;
const b500 = 1.91594743830e-4;
const b001 = 2.42624687470e-5;
const b011 = -9.56770881560e-6;
const b021 = -2.36783083610e-7;
const b031 = -3.45587736550e-6;
const b041 = 1.29567177830e-6;
const b101 = -6.95849219480e-5;
const b111 = 2.22016695300e-5;
const b121 = 5.85666925900e-6;
const b131 = 6.33106121560e-7;
const b201 = 1.12412331915e-4;
const b211 = -2.95341353532e-5;
const b221 = -1.46478417600e-6;
const b301 = -6.92888744480e-5;
const b311 = 1.03636901040e-5;
const b401 = 1.54637136265e-5;
const b002 = -5.84844329840e-7;
const b012 = -5.56991545570e-6;
const b022 = 3.91373870800e-7;
const b032 = 7.76188880920e-9;
const b102 = -9.62445031940e-6;
const b112 = 1.09241497668e-5;
const b122 = -1.31462208134e-6;
const b202 = 1.47789320994e-5;
const b212 = -4.06325568810e-6;
const b302 = -7.12478989080e-6;
const c000 = -6.07991438090e-5;
const c001 = 1.99712338438e-5;
const c002 = -3.39280843110e-6;
const c003 = 4.21246123200e-7;
const c004 = -6.32363064300e-8;
const c005 = 1.17681023580e-8;
const c010 = 1.85057654290e-5;
const c011 = -2.34727734620e-6;
const c012 = -1.09581019659e-6;
const c013 = 1.25816399608e-6;
const c020 = -1.17166068530e-5;
const c021 = 4.26100574800e-6;
const c022 = 8.60877154770e-7;
const c030 = 7.92796561730e-6;
const c031 = -9.22650800740e-7;
const c040 = -3.41021874820e-6;
const c041 = -1.26705833028e-7;
const c050 = 5.07367668140e-7;
const c100 = 2.42624687470e-5;
const c101 = -1.16968865968e-6;
const c102 = 1.08930565545e-6;
const c103 = -4.45885016920e-7;
const c110 = -9.56770881560e-6;
const c111 = -1.11398309114e-5;
const c112 = -8.18870887110e-7;
const c120 = -2.36783083610e-7;
const c121 = 7.82747741600e-7;
const c130 = -3.45587736550e-6;
const c131 = 1.55237776184e-8;
const c140 = 1.29567177830e-6;
const c200 = -3.47924609740e-5;
const c201 = -9.62445031940e-6;
const c202 = 5.02389113400e-8;
const c210 = 1.11008347650e-5;
const c211 = 1.09241497668e-5;
const c220 = 2.92833462950e-6;
const c221 = -1.31462208134e-6;
const c230 = 3.16553060780e-7;
const c300 = 3.74707773050e-5;
const c301 = 9.85262139960e-6;
const c310 = -9.84471178440e-6;
const c311 = -2.70883712540e-6;
const c320 = -4.88261392000e-7;
const c400 = -1.73222186120e-5;
const c401 = -3.56239494540e-6;
const c410 = 2.59092252600e-6;
const c500 = 3.09274272530e-6;
const h001 = 1.07699958620e-3;
const h002 = -3.03995719050e-5;
const h003 = 3.32853897400e-6;
const h004 = -2.82734035930e-7;
const h005 = 2.10623061600e-8;
const h006 = -2.10787688100e-9;
const h007 = 2.80192913290e-10;
const h011 = -1.56497346750e-5;
const h012 = 9.25288271450e-6;
const h013 = -3.91212891030e-7;
const h014 = -9.13175163830e-8;
const h015 = 6.29081998040e-8;
const h021 = 2.77621064840e-5;
const h022 = -5.85830342650e-6;
const h023 = 7.10167624670e-7;
const h024 = 7.17397628980e-8;
const h031 = -1.65211592590e-5;
const h032 = 3.96398280870e-6;
const h033 = -1.53775133460e-7;
const h042 = -1.70510937410e-6;
const h043 = -2.11176388380e-8;
const h041 = 6.91113227020e-6;
const h051 = -8.05396155400e-7;
const h052 = 2.53683834070e-7;
const h061 = 2.05430942680e-7;
const h101 = -3.10389819760e-4;
const h102 = 1.21312343735e-5;
const h103 = -1.94948109950e-7;
const h104 = 9.07754712880e-8;
const h105 = -2.22942508460e-8;
const h111 = 3.50095997640e-5;
const h112 = -4.78385440780e-6;
const h113 = -1.85663848520e-6;
const h114 = -6.82392405930e-8;
const h121 = -3.74358423440e-5;
const h122 = -1.18391541805e-7;
const h123 = 1.30457956930e-7;
const h131 = 2.41414794830e-5;
const h132 = -1.72793868275e-6;
const h133 = 2.58729626970e-9;
const h141 = -8.75958731540e-6;
const h142 = 6.47835889150e-7;
const h151 = -3.30527589000e-7;
const h201 = 6.69280670380e-4;
const h202 = -1.73962304870e-5;
const h203 = -1.60407505320e-6;
const h204 = 4.18657594500e-9;
const h211 = -4.35926785610e-5;
const h212 = 5.55041738250e-6;
const h213 = 1.82069162780e-6;
const h221 = 3.59078227600e-5;
const h222 = 1.46416731475e-6;
const h223 = -2.19103680220e-7;
const h231 = -1.43536330480e-5;
const h232 = 1.58276530390e-7;
const h241 = 4.37036805980e-6;
const h301 = -8.50479339370e-4;
const h302 = 1.87353886525e-5;
const h303 = 1.64210356660e-6;
const h311 = 3.45324618280e-5;
const h312 = -4.92235589220e-6;
const h313 = -4.51472854230e-7;
const h321 = -1.86985841870e-5;
const h322 = -2.44130696000e-7;
const h331 = 2.28633245560e-6;
const h401 = 5.80860699430e-4;
const h402 = -8.66110930600e-6;
const h403 = -5.93732490900e-7;
const h411 = -1.19594097880e-5;
const h421 = 3.85953392440e-6;
const h412 = 1.29546126300e-6;
const h501 = -2.10923705070e-4;
const h502 = 1.54637136265e-6;
const h511 = 1.38645945810e-6;
const h601 = 3.19324573050e-5;
const v000 = 1.0769995862e-3;
const v001 = -6.0799143809e-5;
const v002 = 9.9856169219e-6;
const v003 = -1.1309361437e-6;
const v004 = 1.0531153080e-7;
const v005 = -1.2647261286e-8;
const v006 = 1.9613503930e-9;
const v010 = -3.1038981976e-4;
const v011 = 2.4262468747e-5;
const v012 = -5.8484432984e-7;
const v013 = 3.6310188515e-7;
const v014 = -1.1147125423e-7;
const v020 = 6.6928067038e-4;
const v021 = -3.4792460974e-5;
const v022 = -4.8122251597e-6;
const v023 = 1.6746303780e-8;
const v030 = -8.5047933937e-4;
const v031 = 3.7470777305e-5;
const v032 = 4.9263106998e-6;
const v040 = 5.8086069943e-4;
const v041 = -1.7322218612e-5;
const v042 = -1.7811974727e-6;
const v050 = -2.1092370507e-4;
const v051 = 3.0927427253e-6;
const v060 = 3.1932457305e-5;
const v100 = -1.5649734675e-5;
const v101 = 1.8505765429e-5;
const v102 = -1.1736386731e-6;
const v103 = -3.6527006553e-7;
const v104 = 3.1454099902e-7;
const v110 = 3.5009599764e-5;
const v111 = -9.5677088156e-6;
const v112 = -5.5699154557e-6;
const v113 = -2.7295696237e-7;
const v120 = -4.3592678561e-5;
const v121 = 1.1100834765e-5;
const v122 = 5.4620748834e-6;
const v130 = 3.4532461828e-5;
const v131 = -9.8447117844e-6;
const v132 = -1.3544185627e-6;
const v140 = -1.1959409788e-5;
const v141 = 2.5909225260e-6;
const v150 = 1.3864594581e-6;
const v200 = 2.7762106484e-5;
const v201 = -1.1716606853e-5;
const v202 = 2.1305028740e-6;
const v203 = 2.8695905159e-7;
const v210 = -3.7435842344e-5;
const v211 = -2.3678308361e-7;
const v212 = 3.9137387080e-7;
const v220 = 3.5907822760e-5;
const v221 = 2.9283346295e-6;
const v222 = -6.5731104067e-7;
const v230 = -1.8698584187e-5;
const v231 = -4.8826139200e-7;
const v240 = 3.8595339244e-6;
const v300 = -1.6521159259e-5;
const v301 = 7.9279656173e-6;
const v302 = -4.6132540037e-7;
const v310 = 2.4141479483e-5;
const v311 = -3.4558773655e-6;
const v312 = 7.7618888092e-9;
const v320 = -1.4353633048e-5;
const v321 = 3.1655306078e-7;
const v330 = 2.2863324556e-6;
const v400 = 6.9111322702e-6;
const v401 = -3.4102187482e-6;
const v402 = -6.3352916514e-8;
const v410 = -8.7595873154e-6;
const v411 = 1.2956717783e-6;
const v420 = 4.3703680598e-6;
const v500 = -8.0539615540e-7;
const v501 = 5.0736766814e-7;
const v510 = -3.3052758900e-7;
const v600 = 2.0543094268e-7;
const c0 = 0.017947064327968736;
const c1 = -6.076099099929818;
const c2 = 4.883198653547851;
const c3 = -11.88081601230542;
const c4 = 13.34658511480257;
const c5 = -8.722761043208607;
const c6 = 2.082038908808201;
const c7 = -7.389420998107497;
const c8 = -2.110913185058476;
const c9 = 0.2295491578006229;
const c10 = -0.9891538123307282;
const c11 = -0.08987150128406496;
const c12 = 0.3831132432071728;
const c13 = 1.054318231187074;
const c14 = 1.065556599652796;
const c15 = -0.7997496801694032;
const c16 = 0.3850133554097069;
const c17 = -2.078616693017569;
const c18 = 0.8756340772729538;
const c19 = -2.079022768390933;
const c20 = 1.596435439942262;
const c21 = 0.1338002171109174;
const c22 = 1.242891021876471;
const a = 0.014289763856964;
const b = 0.057000649899720;
const t0 = 0.002519;
const t1 = -5.946302841607319;
const t2 = 4.136051661346983;
const t3 = -1.115150523403847e1;
const t4 = 1.476878746184548e1;
const t5 = -1.088873263630961e1;
const t6 = 2.961018839640730;
const t7 = -7.433320943962606;
const t8 = -1.561578562479883;
const t9 = 4.073774363480365e-2;
const t10 = 1.158414435887717e-2;
const t11 = -4.122639292422863e-1;
const t12 = -1.123186915628260e-1;
const t13 = 5.715012685553502e-1;
const t14 = 2.021682115652684e-1;
const t15 = 4.140574258089767e-2;
const t16 = -6.034228641903586e-1;
const t17 = -1.205825928146808e-2;
const t18 = -2.812172968619369e-1;
const t19 = 1.877244474023750e-2;
const t20 = -1.204395563789007e-1;
const t21 = 2.349147739749606e-1;
const t22 = 2.748444541144219e-3;

export function specvol(sa: number, ct: number, p: number): number {
let xs, ys, z, value;

        xs      = Math.sqrt(gsw_sfac*sa + offset);
        ys      = ct*0.025;
        z       = p*1e-4;

        value = v000
    + xs*(v010 + xs*(v020 + xs*(v030 + xs*(v040 + xs*(v050
    + v060*xs))))) + ys*(v100 + xs*(v110 + xs*(v120 + xs*(v130 + xs*(v140
    + v150*xs)))) + ys*(v200 + xs*(v210 + xs*(v220 + xs*(v230 + v240*xs)))
    + ys*(v300 + xs*(v310 + xs*(v320 + v330*xs)) + ys*(v400 + xs*(v410
    + v420*xs) + ys*(v500 + v510*xs + v600*ys))))) + z*(v001 + xs*(v011
    + xs*(v021 + xs*(v031 + xs*(v041 + v051*xs)))) + ys*(v101 + xs*(v111
    + xs*(v121 + xs*(v131 + v141*xs))) + ys*(v201 + xs*(v211 + xs*(v221
    + v231*xs)) + ys*(v301 + xs*(v311 + v321*xs) + ys*(v401 + v411*xs
    + v501*ys)))) + z*(v002 + xs*(v012 + xs*(v022 + xs*(v032 + v042*xs)))
    + ys*(v102 + xs*(v112 + xs*(v122 + v132*xs)) + ys*(v202 + xs*(v212
    + v222*xs) + ys*(v302 + v312*xs + v402*ys))) + z*(v003 + xs*(v013
    + v023*xs) + ys*(v103 + v113*xs + v203*ys) + z*(v004 + v014*xs + v104*ys
    + z*(v005 + v006*z)))));

        return (value);
}

export function alpha(sa: number, ct: number, p: number): number {
let xs, ys, z, v_ct_part;

        xs      = Math.sqrt(gsw_sfac*sa + offset);
        ys      = ct*0.025;
        z       = p*1e-4;

        v_ct_part = a000
                + xs*(a100 + xs*(a200 + xs*(a300 + xs*(a400 + a500*xs))))
                + ys*(a010 + xs*(a110 + xs*(a210 + xs*(a310 + a410*xs)))
                + ys*(a020 + xs*(a120 + xs*(a220 + a320*xs)) + ys*(a030
                + xs*(a130 + a230*xs) + ys*(a040 + a140*xs + a050*ys ))))
                + z*(a001 + xs*(a101 + xs*(a201 + xs*(a301 + a401*xs)))
                + ys*(a011 + xs*(a111 + xs*(a211 + a311*xs)) + ys*(a021
                + xs*(a121 + a221*xs) + ys*(a031 + a131*xs + a041*ys)))
                + z*(a002 + xs*(a102 + xs*(a202 + a302*xs)) + ys*(a012
                + xs*(a112 + a212*xs) + ys*(a022 + a122*xs + a032*ys))
                + z*(a003 + a103*xs + a013*ys + a004*z)));

        return (0.025*v_ct_part/specvol(sa,ct,p));
}

export function beta(sa: number, ct: number, p: number): number {
let xs, ys, z, v_sa_part;

        xs      = Math.sqrt(gsw_sfac*sa + offset);
        ys      = ct*0.025;
        z       = p*1e-4;

        v_sa_part = b000
                + xs*(b100 + xs*(b200 + xs*(b300 + xs*(b400 + b500*xs))))
                + ys*(b010 + xs*(b110 + xs*(b210 + xs*(b310 + b410*xs)))
                + ys*(b020 + xs*(b120 + xs*(b220 + b320*xs)) + ys*(b030
                + xs*(b130 + b230*xs) + ys*(b040 + b140*xs + b050*ys))))
                + z*(b001 + xs*(b101 + xs*(b201 + xs*(b301 + b401*xs)))
                + ys*(b011 + xs*(b111 + xs*(b211 + b311*xs)) + ys*(b021
                + xs*(b121 + b221*xs) + ys*(b031 + b131*xs + b041*ys)))
                + z*(b002 + xs*(b102 + xs*(b202 + b302*xs))+ ys*(b012
                + xs*(b112 + b212*xs) + ys*(b022 + b122*xs + b032*ys))
                + z*(b003 +  b103*xs + b013*ys + b004*z)));

        return (-v_sa_part*0.5*gsw_sfac/(specvol(sa,ct,p)*xs));
}

export function sound_speed(sa: number, ct: number, p: number): number {
let v, v_p, xs, ys, z;

        xs      = Math.sqrt(gsw_sfac*sa + offset);
        ys      = ct*0.025;
        z       = p*1e-4;

        v       = v000
    + xs*(v010 + xs*(v020 + xs*(v030 + xs*(v040 + xs*(v050
    + v060*xs))))) + ys*(v100 + xs*(v110 + xs*(v120 + xs*(v130 + xs*(v140
    + v150*xs)))) + ys*(v200 + xs*(v210 + xs*(v220 + xs*(v230 + v240*xs)))
    + ys*(v300 + xs*(v310 + xs*(v320 + v330*xs)) + ys*(v400 + xs*(v410
    + v420*xs) + ys*(v500 + v510*xs + v600*ys))))) + z*(v001 + xs*(v011
    + xs*(v021 + xs*(v031 + xs*(v041 + v051*xs)))) + ys*(v101 + xs*(v111
    + xs*(v121 + xs*(v131 + v141*xs))) + ys*(v201 + xs*(v211 + xs*(v221
    + v231*xs)) + ys*(v301 + xs*(v311 + v321*xs) + ys*(v401 + v411*xs
    + v501*ys)))) + z*(v002 + xs*(v012 + xs*(v022 + xs*(v032 + v042*xs)))
    + ys*(v102 + xs*(v112 + xs*(v122 + v132*xs)) + ys*(v202 + xs*(v212
    + v222*xs) + ys*(v302 + v312*xs + v402*ys))) + z*(v003 + xs*(v013
    + v023*xs) + ys*(v103 + v113*xs + v203*ys) + z*(v004 + v014*xs + v104*ys
    + z*(v005 + v006*z)))));

        v_p     = c000
    + xs*(c100 + xs*(c200 + xs*(c300 + xs*(c400 + c500*xs))))
    + ys*(c010 + xs*(c110 + xs*(c210 + xs*(c310 + c410*xs))) + ys*(c020
    + xs*(c120 + xs*(c220 + c320*xs)) + ys*(c030 + xs*(c130 + c230*xs)
    + ys*(c040 + c140*xs + c050*ys)))) + z*(c001 + xs*(c101 + xs*(c201
    + xs*(c301 + c401*xs))) + ys*(c011 + xs*(c111 + xs*(c211 + c311*xs))
    + ys*(c021 + xs*(c121 + c221*xs) + ys*(c031 + c131*xs + c041*ys)))
    + z*( c002 + xs*(c102 + c202*xs) + ys*(c012 + c112*xs + c022*ys)
    + z*(c003 + c103*xs + c013*ys + z*(c004 + c005*z))));

        return (10000.0*Math.sqrt(-v*v/v_p));
}

export function sigma0(sa: number, ct: number): number {
let vp0, xs, ys;

        xs      = Math.sqrt(gsw_sfac*sa + offset);
        ys      = ct*0.025;

        vp0     = v000
    + xs*(v010 + xs*(v020 + xs*(v030 + xs*(v040 + xs*(v050
    + v060*xs))))) + ys*(v100 + xs*(v110 + xs*(v120 + xs*(v130 + xs*(v140
    + v150*xs)))) + ys*(v200 + xs*(v210 + xs*(v220 + xs*(v230 + v240*xs)))
    + ys*(v300 + xs*(v310 + xs*(v320 + v330*xs)) + ys*(v400 + xs*(v410
    + v420*xs) + ys*(v500 + v510*xs + v600*ys)))));

        return (1.0/vp0 - 1000.0);
}

export function specvol_sso_0(p: number): number {
let z, return_value;

        z = p*1.0e-4;

        return_value = 9.726613854843870e-04 + z*(-4.505913211160929e-05
                + z*(7.130728965927127e-06 + z*(-6.657179479768312e-07
                + z*(-2.994054447232880e-08 + z*(v005 + v006*z)))));
        return (return_value);
}

export function enthalpy_sso_0(p: number): number {
let dynamic_enthalpy_sso_0_p, z;

        z = p*1.0e-4;

        dynamic_enthalpy_sso_0_p =
                        z*( 9.726613854843870e-4 + z*(-2.252956605630465e-5
                        + z*( 2.376909655387404e-6 + z*(-1.664294869986011e-7
                        + z*(-5.988108894465758e-9 + z*(h006 + h007*z))))));
        return (dynamic_enthalpy_sso_0_p*db2pa*1.0e4);
}

export function grav(lat: number, p: number): number {
let x, sin2, gs, z;

        x       = Math.sin(lat*deg2rad);  /* convert to radians */
        sin2    = x*x;
        gs      = 9.780327*(1.0 + (5.2792e-3 + (2.32e-5*sin2))*sin2);

        z       = z_from_p(p,lat, 0, 0);

        return (gs*(1.0 - gamma*z));    /* z is the height corresponding to p.
                                           Note. In the ocean z is negative. */
}

export function ct_freezing_poly(sa: number, p: number, saturation_fraction: number): number {
let p_r, sa_r, x, return_value;

        sa_r    = sa*1.0e-2;
        x       = Math.sqrt(sa_r);
        p_r     = p*1.0e-4;

        return_value = c0
    + sa_r*(c1 + x*(c2 + x*(c3 + x*(c4 + x*(c5 + c6*x)))))
    + p_r*(c7 + p_r*(c8 + c9*p_r)) + sa_r*p_r*(c10 + p_r*(c12
    + p_r*(c15 + c21*sa_r)) + sa_r*(c13 + c17*p_r + c19*sa_r)
    + x*(c11 + p_r*(c14 + c18*p_r) + sa_r*(c16 + c20*p_r + c22*sa_r)));

        /* Adjust for the effects of dissolved air */
        return_value = return_value - saturation_fraction*
                 (1e-3)*(2.4 - a*sa)*(1.0 + b*(1.0 - sa/gsw_sso));

        return (return_value);
}

export function z_from_p(p: number, lat: number, geo_strf_dyn_height: number, sea_surface_geopotential: number): number {
let x, sin2, b, c, a;

        x       = Math.sin(lat*deg2rad);
        sin2    = x*x;
        b       = 9.780327*(1.0 + (5.2792e-3 + (2.32e-5*sin2))*sin2);
        a       = -0.5*gamma*b;
        c       = enthalpy_sso_0(p)
                  - (geo_strf_dyn_height + sea_surface_geopotential);

        return (-2.0*c/(b + Math.sqrt(b*b - 4.0*a*c)));
}

export function p_from_z(z: number, lat: number, geo_strf_dyn_height: number, sea_surface_geopotential: number): number {
let sinlat, sin2, gs, c1, p, df_dp, f, p_old, p_mid;

    if (z > 5) return GSW_INVALID_VALUE;

    sinlat = Math.sin(lat*deg2rad);
    sin2 = sinlat*sinlat;
    gs = 9.780327*(1.0 + (5.2792e-3 + (2.32e-5*sin2))*sin2);

    /* get the first estimate of p from Saunders (1981) */
    c1 =  5.25e-3*sin2 + 5.92e-3;
    p  = -2.0*z/((1-c1) + Math.sqrt((1-c1)*(1-c1) + 8.84e-6*z)) ;
    /* end of the first estimate from Saunders (1981) */

    df_dp = db2pa*specvol_sso_0(p); /* initial value of the derivative of f */

    f = enthalpy_sso_0(p) + gs*(z - 0.5*gamma*(z*z))
        - (geo_strf_dyn_height + sea_surface_geopotential);
    p_old = p;
    p = p_old - f/df_dp;
    p_mid = 0.5*(p + p_old);
    df_dp = db2pa*specvol_sso_0(p_mid);
    p = p_old - f/df_dp;

    return p;
}

